# Netlify build configuration for Astro
[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--legacy-peer-deps"

# Redirect all requests to index.html (for client-side routing)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
