# Netlify build configuration for Astro
[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

# Redirect all routes to index.html for SPA behavior
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
