# ✅ /netlify.toml
# Configuration for deploying Astro + Serverless AI Analyzer on Netlify

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Ensure all routes (including Astro pages) fallback to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) Set environment variables for clarity
[template.environment]
  GEMINI_API_KEY = "GEMINI_API_KEY"  # 🔑 Replace this in Netlify Dashboard, not here
